### ISSUE TITLE
can't checkout deps/spoa commit hash

### ISSUE THREAD

**Issue by maximilianpress** [pangenome/smoothxg#125]
OS: CentOS Linux release 7.9.2009 (Core)

Got an error in cloning the submodule spoa following the recommended cloning procedure:
```
git clone --recursive https://github.com/pangenome/smoothxg.git

...
Cloning into 'deps/spoa'...
remote: Enumerating objects: 1261, done.
remote: Counting objects: 100% (177/177), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 1261 (delta 104), reused 116 (delta 56), pack-reused 1084
Receiving objects: 100% (1261/1261), 502.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (848/848), done.
fatal: reference is not a tree: d3daa963a4b32826ec98a4642e702ffe1991ae81
Unable to checkout 'd3daa963a4b32826ec98a4642e702ffe1991ae81' in submodule path 'deps/spoa'
```

Based on what I read [here](https://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error) it seems like that commit is detached. If I directly try to check out the commit as that answer suggests, it again fails on the same error.

Without this dependency installed, it seems like one can't subsequently build smoothxg. I will continue to work at this a little and update if I figure it out.

**Comment by subwaystation** [comment]
Hi @maximilianpress 
I just did `git clone --recursive https://github.com/pangenome/smoothxg.git` and it worked smoothly for me. In the following log file, there is no `fatal` error:
[smoothxg_i125.txt](https://github.com/pangenome/smoothxg/files/6692603/smoothxg_i125.txt)
Sorry, I can't reproduce. Maybe your version of `git` is the problem?

**Comment by maximilianpress** [comment]
Hmmm, that is unfortunately a possibility, I do not control my git version. Thanks for checking; I'll go ahead and close if it's just me.
