### ISSUE TITLE
Provide version number in --help or add new --version argument

### ISSUE THREAD

**Issue by heuermh** [pangenome/smoothxg#147]
For https://github.com/nf-core/pangenome/issues/70 and https://github.com/nf-core/modules/issues/1133 it would be desireable to have `smoothxg` provide its version number in the `--help` output or preferably in a new `--version` argument.

**Comment by AndreaGuarracino** [comment]
Hi @heuermh, such a feature was recently added in #146 (`smoothxg --version`). Soon in `bioconda`.
