### ISSUE TITLE
smoothxg crashes with signal 7

### ISSUE THREAD

**Issue by cgroza** [pangenome/smoothxg#161]
Hi,

I am attempting to smooth a genome graph created by the pggb pipeline on 348 genomes (HPRC + 252 trios + hg38 + chm13v2) on a chromosome by chromosome run.
However, for most larger chromosomes, smoothxg consistently crashes with signal 7.
The compute node never runs out of memory.
Has smoothxg even been tested on inputs of this size?
What debugging leads do you suggest?

Thank you in advance.
Cristian Groza

**Comment by ekg** [comment]
Is the output in a local scratch directory?

A possible issue is our use of temporary files on diak. You can specify
/tmp or /dev/shm to make sure the process isn't being killed for writing
too much data to a network filesystem. That's very speculative.

I would talk with your sysadmins about what might be happening. Please let
us know.

**Comment by AndreaGuarracino** [comment]
@cgroza, thank you for investigating it. Are you using an updated version of `pggb`? Recently, we added this parameter

```
    -D, --temp-dir PATH         directory for temporary files
```

When this is not specified, all temporary stuff should live in the directory specified with `-o/--output-dir`, but this is not true with older `pggb` version.
