### ISSUE TITLE
zstdutil.hpp:14:10: fatal error: zstd.h: No such file or directory

### ISSUE THREAD

**Issue by bredeson** [pangenome/smoothxg#167]
Hi smoothxg dev(s),
I have been attempting to build a pangenome from 5 haplotypes (~20Mb each) for a single chromosome with pggb. pggb (conda install of pggb=0.3.0, smoothxg=0.6.1 on SUSE 5.3.18-24.107-default) gets to the smoothxg step and throws an 'Illegal Instruction' error (exit 132). So, I thought I would try compiling from source; however, cmake can't find zstd.h when attempting to compile zstdutil.hpp (even though the path is specified in `$INCLUDE_PATH`). 

The cmake error:
```
In file included from REDACTED/smoothxg/src/smooth.hpp:16,
                 from REDACTED/smoothxg/src/breaks.cpp:5:
REDACTED/smoothxg/src/zstdutil.hpp:14:10: fatal error: zstd.h: No such file or directory
   14 | #include <zstd.h>
      |          ^~~~~~~~
compilation terminated.
```

I've tried specifying the location of the zstd.h directory explicitly using the variations suggested [here](https://stackoverflow.com/questions/25849571/adding-include-directories-to-cmake-when-calling-it-from-the-command-line).

Your help would be immensely appreciated.

-Jessen

**Comment by ekg** [comment]
If possible can you follow the setup in the Dockerfile? You'll probably
need to be on Ubuntu or a debian system to do this trivially. You're
missing some development libraries that the system depends on.
Alternatively, and easier, just build the docker image using the
Dockerfile. This will give you a locally built version of the pipeline.
Make sure to do this on your target system.

**Comment by bredeson** [comment]
Hi,
I was able to successfully compile the software by specifying the install location of `zstd.h` in the CMakeLists with `include_directories()`.
