### ISSUE TITLE
"Assertion `idx <this->size()' failed"  interpretation

### ISSUE THREAD

**Issue by sivico26** [pangenome/smoothxg#182]
Hello there, thanks for developing `smoothxg`

I want to smooth a graph I generated using `cactus` (the progressive algorithm, because my data consists of several species of the same genera) and then used `hal2vg` and `vg convert` to obtain a `.gfa` graph (which is the input for `smoothxg`). The graph is massive by the way (75 Gbytes).

This is the command I am using

```bash
smoothxg -t $threads -r $haps -g $graph -o graph_smoothed.gfa
```

While running it, I am getting this error:

```
[smoothxg::(1-1)::main] loading graph
[smoothxg::(1-1)::main] prepping graph for smoothing
[odgi::gfa_to_handle] building nodes:                      ## Omitted for brevity
[odgi::gfa_to_handle] building edges:                      ## Omitted for brevity
[smoothxg::(1-1)::prep] building path index
smoothxg: /opt/conda/conda-bld/smoothxg_1671059618733/work/build/odgi-prefix/src/odgi-build/sdsl-lite-prefix/src/sdsl-lite-build/include/sdsl/int_vector.hpp:1360: sdsl::int_vector<<anonymous> >::referencesdsl::int_vector<<anonymous>>::operator[(const size_type&) [with unsigned char t_width = 1; sdsl::int_vector<<anonymous> >::reference = sdsl::int_vector_reference<sdsl::int_vector<1> >; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]: Assertion `idx <this->size()' failed.
```

Clearly, there is an assertion (testing a condition?) that is not normal and the program prefers to exit rather than proceed. However, I can not tell what is being tested. Can you help me to interpret the assertion?

Thanks in advance
Sivico

**Comment by AndreaGuarracino** [comment]
Can you show a small part of your GFA? Just the beginning of the first path would be enough.

Are there P lines or W lines?

**Comment by sivico26** [comment]
Well that was easy! The graph does not have any paths (P lines) so that is the issue. My bad.

Thanks for the help and the speedy response @AndreaGuarracino! I will be back with a real issue soon.
