### ISSUE TITLE
"Error in cg_backtrack" strikes again

### ISSUE THREAD

**Issue by sivico26** [pangenome/smoothxg#184]
Hi `smoothxg` team,

I am trying to use `smoothxg` to smooth a huge graph (~131 Gbytes in `.gfa`) from seven haplotypes of different species of the same genera. Although they are just a few individuals the genomes are big (~4 Gb) and I think the divergence between the species added a lot of variation to the graph. I built the graph using progressive `cactus` and transformed the alignment using `hal2vg` and `vg convert` to get the `.gfa`.  

In any case, I am now trying to smooth the graph and I am running `smoothxg` like this:

```bash
smoothxg -t $threads -T 10 -r 7 -g $graph -o $graph
```

But I consistently get the following error (I chopped the progress messages to make it more readable):

```raw
[smoothxg::(1-1)::main] loading graph
[smoothxg::(1-1)::main] prepping graph for smoothing
[odgi::gfa_to_handle] building nodes:  0.00% @ 3.70e+04/s elapsed: 00:00:00:00 remain: 00:08:46:56
[odgi::gfa_to_handle] building edges:  0.00% @ 1.06e-01/s elapsed: 00:00:02:12 remain: 186042:-3:-14:-8
[odgi::gfa_to_handle] building paths:  2.04% @ 4.55e-03/s elapsed: 00:00:03:39 remain: 00:02:55:57
[smoothxg::(1-1)::prep] building path index
[smoothxg::(1-1)::prep] path_sgd_zipf_space_max: 100
[smoothxg::(1-1)::prep] path_sgd_zipf_max_number_of_distributions: 101
[smoothxg::(1-1)::prep] sorting graph
[odgi::path_linear_sgd] calculating linear SGD schedule (5.06e-17 1.00e+00 100 0 1.00e-02)
[odgi::path_linear_sgd] calculating zetas for 102 zipf distributions
[odgi::path_linear_sgd] 1D path-guided SGD:  0.00% @ 4.32e+00/s elapsed: 00:00:03:51 remain: 1486155:-3:-14:-8
[odgi::groom] grooming:  0.00% @ 8.82e+03/s elapsed: 00:00:00:00 remain: 01:12:50:43
[odgi::groom] organizing handles:  0.00% @ 9.88e+03/s elapsed: 00:00:00:00 remain: 01:08:53:03
[odgi::groom] flipped 575715961 handles
[odgi::topological_order] sorting nodes:  0.00% @ 5.25e+05/s elapsed: 00:00:00:00 remain: 00:00:37:10
[smoothxg::(1-1)::prep] chopping graph to 100
[odgi::chop] 7019135 node(s) to chop.
[smoothxg::(1-1)::prep] writing graph hordeum.gfa.prep.0.gfa
[smoothxg::(1-1)::main] building xg index
[smoothxg::(1-1)::smoothable_blocks] computing blocks
[smoothxg::(1-1)::smoothable_blocks] computing blocks for 1299159437 handles:  0.00% @ 2.08e+05/s elapsed: 00:00:00:00 remain: 00:01:43:56
[smoothxg::(1-1)::break_and_split_blocks] cutting blocks that contain sequences longer than max-poa-length (8000) and depth >= 0
[smoothxg::(1-1)::break_and_split_blocks] splitting 9500080 blocks at identity 0.000 (WFA-based clustering) and at estimated-identity 0.000 (mash-based clustering)
[smoothxg::(1-1)::break_and_split_blocks] cutting and splitting 9500080 blocks:  0.00% @ 2.34e+02/s elapsed: 00:00:00:00 remain: 00:11:17:24
[smoothxg::(1-1)::break_and_split_blocks] cut 568 blocks of which 15 had repeats
[smoothxg::(1-1)::break_and_split_blocks] split 0 blocks
[smoothxg::(1-1)::smooth_and_lace] applying local abPOA to 9500080 blocks:  0.00% @ 2.01e+01/s elapsed: 00:00:00:00 remain: 05:11:24:37 [...]  [simd_abpoa_align_sequence_to_subgraph] Error in cg_backtrack.
[smoothxg::(1-1)::smooth_and_lace] applying local abPOA to 9500080 blocks:  0.07% @ 1.22e+02/s elapsed: 00:00:00:52 remain: 00:21:42:03
```

You can see the problem is `Error in cg_backtrack`. I am aware this is a known error (#19), but it has been a while now. What are the current recommendations to tackle this problem? Can I parametrize `smoothxg` somehow to bypass it? Should I ask @yangao07 instead? 

Alternatively, is there alternative processing that I can do to "smooth the graph"? My goal is to explore the graph for some atypical SVs.

Your thoughts are highly appreciated,
Sivico

**Comment by AndreaGuarracino** [comment]
You have two ways to avoid the problem:
1) use abPOA in global mode by adding the `-Z` flag; we do not recommend this option, as local mode is much better for the smoothing
2) use SPOA by adding the `-S` flag.

**Comment by ekg** [comment]
The back story is that we are usually only running smoothxg in pggb. We have set `-S` by default there for some time.  Just setting `-S` will fix your issue.

We probably want to improve the default settings in smoothxg though so that it can work correctly on its own. That's a TODO.

**Comment by sivico26** [comment]
Great, thanks for the quick answer @AndreaGuarracino and @ekg. I am going to try it out with `-S` and hope to report back soon!

**Comment by sivico26** [comment]
Hi again. I just wanted to report that using `-S` as discussed solved the issue and `smoothxg` finished successfully after a few days. 

Thanks again for the help.
