### ISSUE TITLE
Change on CLI on v0.7.0

### ISSUE THREAD

**Issue by sivico26** [pangenome/smoothxg#189]
Hi `smoothxg` team,

This should be a fairly small issue. Last week [Depuplicato](https://github.com/pangenome/smoothxg/releases/tag/v0.7.0) (v0.7) version was released promising great performance improvements. 

Of course, I have to try that! So I submitted again a couple of big jobs I am running (using abPOA and SPOA) and I found that one died fairly quickly. When I checked, I found that I use a parameter that the CLI didn't get `-S`.  That is when I realized that the CLI changed from Ciclico (v0.6.8) to Deduplicato (v0.7.0). The default poa algorithm changed from abPOA to SPOA (something that I remember being discussed in previous issues) and the `-S` flag changed to `-A`. 

From a CLI design point of view, this makes sense to me. However, it does break backward compatibility. I do not necessarily have a problem with that, but I do think this should be communicated more clearly, ideally on the [release](https://github.com/pangenome/smoothxg/releases/tag/v0.7.0) introduction. In my case, if I had not run both jobs, probably I would not have noticed those changes, and I would be running a different POA algorithm without noticing until who knows when. 

Keep up the good work!
Cheers

P.S. I just noticed that the [README](https://github.com/pangenome/smoothxg#notes-for-debugging) still cites `-A` for debugging purposes but this clearly disappeared in the latest version, along with `-B`.

**Comment by AndreaGuarracino** [comment]
![Youreright](https://user-images.githubusercontent.com/62253982/232798913-9a0e68cc-ca16-4253-83a1-2bc2ae7a3944.png)

I've update the [release](https://github.com/pangenome/smoothxg/releases/tag/v0.7.0) introduction, being also a bit more verbose.

About the README, I've fixed the `-A` flag, that is now `-S`. The debugging options are available only when `smoothxg` is compiled with `-DPOA_DEBUG=ON`.

Thank you for pointing out all these issues!
