### ISSUE TITLE
smoothxg seems to think my xg index is version 33708103 

### ISSUE THREAD

**Issue by Nheyer** [pangenome/smoothxg#3]
I honestly have no idea haw to check what the actual version is, but I assume it is v 14 as it was made with the latest static release of vg, coming from a hal file made by cactus. The error I am geting is :
```
warning [libhandlegraph]: Serialized handle graph does not appear to match deserialzation type.
warning [libhandlegraph]: It is either an old version or in the wrong format.
warning [libhandlegraph]: Attempting to load it anyway. Future releases will reject it!
terminate called after throwing an instance of 'xg::XGFormatError'
  what():  XG index file version 33708103 is too new to interpret (max version = 14)
Aborted (core dumped)
```

**Comment by ekg** [comment]
What's the process that led to this xg file? If it's from vg there may be a risk of incompatibility. 

To get around this you can just give it GFA that's equivalent to the xg file. I may remove xg input in the future if it can't be kept stable (the index is then built during operation of smoothxg).

**Comment by Nheyer** [comment]
sort of the process was :
1. `for region in <list> ; do samtools faidx $region hg38.fa >  ${region}.fa` 
2. `cat *.fa > combined.fa`
3. `mafft combined.fa > combined.msa.fa`
4. `raxml-ng combined.msa.fa`
5. create a Seqfile using the outputs
6. `cactus JobStore input.SeqFile alignments.hal`
7. `hal2vg alignments.hal > alignments.pg`
8. `vg convert alignments.pg -v > alignments.vg`
9. `vg simplify alignments.vg > alignments-simmplified.vg`
10. `vg index alignments-simmplified.vg -x > alignments-simmplified.vg.xg`

**Comment by ekg** [comment]
Use vg view rather than index at the last step to get a GFA and provide
this to smoothxg.

**Comment by Nheyer** [comment]
Thank you so much this might have fixed it, but when I run vg validate  on the resulting smoothed graph I get a message that one of the paths is invalid

**Comment by ekg** [comment]
What does the message say? The graph is validated by smoothxg, so I'm
curious what it thinks the problem is.

**Comment by Nheyer** [comment]
It sayes `graph path 'Notch2NL-A.Notch2NL-A' invalid: edge from 1 end to 2 start does not exist` but this is cryptic to me, but I think it is because there are unconnected sub graphs in the gfa, that seem to be induced by smoothxg   
![this_looks_broken](https://user-images.githubusercontent.com/39816817/93036597-28e35080-f5f5-11ea-8f33-f257383a3fd7.png)

**Comment by ekg** [comment]
Interesting. There must be a mistake in the path embedding. This error indicates that an edge is missing from the graph, but a path traverses it. I will try to debug it from the code and ask if you can re-run. It will be a few days.

**Comment by rickbeeloo** [comment]
I have the same problem I build the index using `odgi build` and got:
> XG index file version 1988148666 is too new to interpret (max version = 14)

I could indeed just pass the `.gfa` but this does not perform the `odgi sort -S` you recommended (as far as I see) before the smoothing.

**Comment by ekg** [comment]
You should pass the GFA and the `-n` flag that says not to do any prep to the graph.

That said, smoothxg is now automatically setting up the graph including chop and the recommended sorting pipeline.

**Comment by rickbeeloo** [comment]
Aah cool! I looked at `prep.cpp` and saw nothing under the comment `// then sort it using a short sorting pipeline equivalent to odgi sort -p Ygs` so thought this was not included yet.
