### ISSUE TITLE
Smoothing of a cactus graph more aggressively

### ISSUE THREAD

**Issue by egoltsman** [pangenome/smoothxg#4]
Hi Erik,
I'm looking at a cactus graph I constructed from a largely homologous 1mb slice from four individuals of the same plant species.  I converted it to vg with hal2vg.  The graph is very branchy, with an average segment length of 19bp.  I'm wondering if smoothxg could be configured to fuse segments over what looks like snp bubbles.  Basically I'm looking to simplify it down to a structure I can visualize, meaning fusing the nodes pretty aggressively.  Is smoothxg a suitable tool for this? 

Right now, after running it with all defaults I go from 

```
Number of segments: 67110
Number of links: 92880
Number of arcs: 185760
Max rank: 0
Total segment length: 1318164
Average segment length: 19.642
Sum of rank-0 segment lengths: 0
Max degree: 6
Average degree: 1.384
```

..to

```
Number of segments: 49558
Number of links: 66996
Number of arcs: 133992
Max rank: 0
Total segment length: 1574935
Average segment length: 31.780
Sum of rank-0 segment lengths: 0
Max degree: 8
Average degree: 1.352
```

Although clearly an improvement, the graph still breaks any visualization tool I've thrown at it.

Thanks!

**Comment by ekg** [comment]
So it's getting bigger in sequence space. Is that what you would like? This
would make it seem that the compressed regions of the graph are being
pulled apart.

You can visualize it with odgi viz. That provides a linear time rendering.
There are a number of options. We are also working on a 2D layout using the
same algorithm (odgi layout) but that's not quite ready yet.

Bandage might be able to handle this. But you'll need a very powerful
desktop.

**Comment by egoltsman** [comment]
Yes, that would be the effect I expect.   It's not just about visualization.  I was also going to compare the snarl-based variant calls on both graphs, smoothed and original, and see which call set does better in detecting large SVs.   When the graph is very "bubbly", the larger variants an be missed and instead reported as a ton of tiny snps and indels.  
Thanks

**Comment by egoltsman** [comment]
As a more general question, should I be calling variants (vg snarls, deconstruct) off of the original cyclic graph or the "smoothed" version?  I had assumed that it was the latter, but perhaps the snarls algorithm deals with the cycles better than I think it does?

**Comment by ekg** [comment]
I would work on the smoothed graph.
