### ISSUE TITLE
Seg fault while generating consensus paths

### ISSUE THREAD

**Issue by brettChapman** [pangenome/smoothxg#44]
Hi Erik

I've been getting seg faults when generating the consensus graphs (parameter -s) when I've ran with whole chromosomes across the 20 genomes. So far it's happened with -C 10 and -C 100. The smoothed graph is output ok, it only seg faults when it gets to creating the different consensus paths with the various jump values of -C. For now I'll need to refrain from using the -s parameter. Could this be a memory efficiency problem or simply generating the graphs is just too memory intensive? Thanks.

```
[smoothxg::create_consensus_graph] deriving consensus graph with consensus-jump-max=100
[smoothxg::create_consensus_graph] finding consensus links
[smoothxg::create_consensus_graph] adding consensus paths
[smoothxg::create_consensus_graph] cleaning up redundant link paths
srun: error: node-7: task 0: Segmentation fault (core dumped)
```

**Comment by ekg** [comment]
There is apparently a memory problem, and there are also some quadratic
aspects of this in the number of paths covering the graph. It needs more
work. No harm to skip it for now.

**Comment by AndreaGuarracino** [comment]
Hi @brettChapman,

thanks for taking smoothxg to the limit! Have you retried the command with the latest versions of smoothxg? Several improvements have been applied, which have also directly and indirectly improved the consensus graph generation.

**Comment by brettChapman** [comment]
Hi @AndreaGuarracino 

I haven't tried the latest version yet. I'm now using smoothxg as part of @ekg PGGB workflow. I'll wait for Erik to update PGGB before attempting to run PGGB again.

**Comment by AndreaGuarracino** [comment]
Hi Brett, we recently successfully applied [pggb](https://github.com/pangenome/pggb) to 90 phased human haplotypes plus 2 references (have a look [here]((https://github.com/pangenome/HPRCy1))).

We had no problems getting the consensus graphs. In particular, the `cleaning up redundant link paths` passage, that was the trickier one, has been totally removed. This has improved execution times and memory requirements too. Hopefully, you are not experiencing segmentation faults anymore.
