### ISSUE TITLE
smoothxg takes gap "-" in the sequence or not

### ISSUE THREAD

**Issue by XuewenWangUGA** [pangenome/smoothxg#46]
I would like to know whether I can use the equal length of sequences with "-" for the gap as input for pbbg step snoothxg. It seems that the alignment and  seqwish in pggb takes "-" but the smoothxg will terminate.
Therefore, is it possible for smoothxg to take gap "-" in the sequence?
Thanks.

**Comment by ekg** [comment]
I would remove these before seqwish. Can you do that or is it problematic
to strip them?

We can update the pieces to handle these padding characters. But just
because it runs doesn't mean you get a sensible output.

**Comment by XuewenWangUGA** [comment]
Erik,
Thank you for reply.
Look forward to see your update.
Happy Thanksgiving.


Xuewen

________________________________

**Comment by ekg** [comment]
To be clear, you should remove them before doing anything, before even
mapping.

Thanks, cheers :)
