### ISSUE TITLE
strange consensus paths 

### ISSUE THREAD

**Issue by Nheyer** [pangenome/smoothxg#7]
so, the consensus blocks that are generated appear to be < 70X smaller then I would expect and align back to the inputs of the original sequences that were used to generate the graph in an alternation pattern i.e. forward - reverse -forward-reverse

**Comment by ekg** [comment]
Very interesting.

I'm not sure about the orientation (that seems plausible, because there isn't anything to pin it down) but keep in mind that the block size isn't only determined by the `-w ` parameter. The blocks will break where there is an edge that jumps `-e` bp in the sort order (this is set low). Also, the `-w` parameter is the total sequence in the graph chunk that's picked up, not the length of the graph region. What's the depth you see / expect in the graph?

**Comment by Nheyer** [comment]
given it is a cactus graph of the NOTCH2NL genes I am expecting at least 70kb  and am getting at max 1kb with most being far less then that, but if I was able to knit the f-r-f-r  and a few that have only 1-10 bp between alignments  it would be past 100kb, for now I think the parameter may help with the latter

**Comment by ekg** [comment]
That's a really interesting and strange issue.

There are definitely some ways to resolve it. The orientation of the consensus paths should match the sort order of the base graph as represented in the fragments of sequence that they pass through (in the other paths).

I can look into this when I'm next working on smoothxg in a few days. I need to make a number of improvements for its memory scalability. I'm also going to produce MAF output directly from each block.

**Comment by ekg** [comment]
I also would like to be able to directly output a consensus graph in GFA. Curious what you think about that. The idea would be to link up all the consensus paths and drop all other variation. It's a little tricky, but I think it will only require a new kind of filter on nodes and edges implemented in odgi/algorithms.

**Comment by Nheyer** [comment]
honestly that would be perfect for what I am looking to do, if there are parts that you would like help with on that I would be glad to help !

**Comment by ekg** [comment]
I'm just now getting to this. We've got MAF output almost running now. The next step is to take the consensus sequences and infer the consensus graph from them.

If you're interested in helping out, what's needed is a filter mode in odgi that removes any edge that isn't connecting two different paths.

Removing paths that aren't labeled `Consensus_*`, then removing nodes that have coverage = 0, then removing edges that don't connect separate paths should nearly get us to a consensus graph.

I think that this probably isn't enough to get this right. We actually would want to check the connection between each consensus path and the other POA blocks that connect to it. We would then need to ensure at least some walk connecting the consensus paths, and not remove this. It's probably "easy" but would require more coding to sort out, and probably a breadth-first search through the graph to find a suitable walk.

**Comment by AndreaGuarracino** [comment]
Tackled in #17, #32, #79, and #82.
