### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by evolgen** [pangenome/smoothxg#80]
Dear developers,

The current installation of smoothxg throws out an error during compilation as below -

```
[ 91%] Building CXX object CMakeFiles/smoothxg_objs.dir/src/breaks.cpp.o
[ 92%] Building CXX object CMakeFiles/smoothxg_objs.dir/src/smooth.cpp.o
/Software/smoothxg/smoothxg/src/smooth.cpp: In function 'odgi::graph_t* smoothxg::smooth_and_lace(const xg::XG&, sm
oothxg::blockset_t*&, int, int, int, int, int, int, bool, int, std::__cxx11::string&, std::__cxx11::string&, bool, bool, double, bool, const st
ring&, std::vector<std::__cxx11::basic_string<char> >&, bool)':
/Software/smoothxg/smoothxg/src/smooth.cpp:1621:49: error: expected '=' before ':' token
         for (auto &merged_block_id_interval_idx : merged_block_id_intervals){
                                                 ^
/Software/smoothxg/smoothxg/src/smooth.cpp:1662:9: error: expected ';' before 'consensus_paths'
         consensus_paths.erase(
```
I am currently using cmake V3.15.1 and gcc V7.4.0. Could you please point out where the issue might be?
Thank you!!!

Rohit

**Comment by subwaystation** [comment]
Dear @evolgen 
From our experience, you will need at least GCC V10.x.x in order to compile smoothxg. Please update your GCC and try again.
Best,
Simon

**Comment by subwaystation** [comment]
Or you can use our docker container from `pggb` which includes `smoothxg`: https://github.com/pangenome/pggb#installation

**Comment by evolgen** [comment]
Hi Simon,
Good to know, thank you. Can you please add the dependencies on the installation page?
I haven't had much success with docker on our cluster, will give it another try.
Cheers,
Rohit

**Comment by evolgen** [comment]
Hi Simon,
I have been able to get the docker version of pggb going, I already have a gfa file from seqwish. Is there a way to extract maf from this gfa using pggb (I don't see a -g option in pggb like smoothxg does)?

**Comment by subwaystation** [comment]
Hi @evolgen 
the `-m/--write-msa-in-maf-format=[FILE]` parameter in `smoothxg` is currently not exposed in `pggb`.  But if you run the whole `pggb` pipeline, you will get the MAF output by default: https://github.com/pangenome/pggb/blob/030a5c5d845a85fdabddc8095a48c689f261a770/pggb#L312

An example, assuming you are in the `pggb` directory.
```
pggb -i data/LPA/LPA.fa.gz -s 10000 -n 10 -p 80 -v -L -S -m -o pggb_LPA -t 4 -W
```

Then I can see:
![image](https://user-images.githubusercontent.com/10184961/106875210-b3c50480-66d6-11eb-9a89-7ebdf692f5c4.png)

Or if you go step by step, you can just set the `-m/--write-msa-in-maf-format=[FILE]` in `smoothxg`.

Cheers :)

**Comment by evolgen** [comment]
Hi Simon,
Thanks for the swift suggestions. I might have to get smoothxg figured out manually since these gfa file generation takes over a month, so I would like to proceed with the existing ones. As of now using gcc-10 and cmake-3.19 seem to work. I am still debugging dependencies on our cluster, will let you know once everything compiles. Thanks again!!!
Cheers,
Rohit

**Comment by subwaystation** [comment]
Hi @evolgen 
you are welcome. 
Maybe a look in our [Dockerfile](https://github.com/pangenome/pggb/blob/4bd28d9e10b5da94a91af88dbef956314f369e0c/Dockerfile#L11) helps you to identify the required dependencies?
Feel free post your experience here, so we can extend our documentation. Thanks!
Best,
Simon
